### ISSUE TITLE
I miss the serverless.yml example

### ISSUE THREAD

**Issue by dpurrington** [Cimpress-MCP/Platform-Authorizer#14]
I was missing an example of how to refer to the custom definition in the serverless.yml file. I needed to dig through the wiki history to find it.  FWIW, I know this isn't intended to be a serverless framework repo, but having multiple examples seems like a good thing. Just my $.02.  :)

**Comment by chrisoverzero** [comment]
Accepted and happily done. I restored from the old edits (which wouldn’t let me at the raw Markdown for some reason), and renamed the pages for SAM and Serverless to be co-equal.

I think I forgot my scope for a bit, there.
