### ISSUE TITLE
Document necessary to access to Serverless Application Repository

### ISSUE THREAD

**Issue by zmarois** [Cimpress-MCP/Platform-Authorizer#27]
To use this package, the user deploying to Lambda needs access to the Serverless Application Repository, but the access to this is relatively obscure.

I'd like to add the following to the wiki, probably in `How-To-Use-It.md`:

```
In both of these cases, the role you are using to deploy to Lambda will need access to perform action CreateCloudFormationTemplate on service AWS Serverless Application Repository for resource arn:aws:serverlessrepo:us-east-1:820870426321:applications/platform-authorizer. Note this is **not for AWS service CloudFormation**, so using a CloudFormation admin policy will not work. There isn't an AWS managed policy which covers access to service AWS Serverless Application Repository, so you will need your own policy for this.
```

As far I as I can tell, there isn't such a thing as PRs to wikis in github and without master access, I can't push my change myself.

**Comment by chrisoverzero** [comment]
Thank you again for taking such an interest. Lemme propose what changes I'd like to make, and please do tell me if they meet your requirements:

1. Obsolete the "How to Use It with Serverless" wiki page, moving the contents of "How to Use It with SAM" to "How to Use It". (Then obsoleting "How to Use It with SAM", natch.)
1. Mark off most of the page's current contents as "Infrastructure Configuration".
1. Add a new section "IAM Configuration", with roughly the following contents:
   
   > The role performing deployment will require a policy (inline or otherwise) with at least the following permissions:
   > 
   > ```json
   > {
   >   "Effect": "Allow",
   >   "Action": [
   >     "serverlessrepo:CreateCloudformationChangeSet",
   >     "serverlessrepo:CreateCloudformationTemplate"
   >   ],
   >   "Resource": "arn:aws:serverlessrepo:us-east-1:820870426321:applications/platform-authorizer"
   > }
   > ```
   > 
   > As of 2021-01-05, there is no AWS managed policy which fits the bill.
   
   I've added a second action only as futureproofing. Upgrading to a later version of the authorizer will require creation of a changeset.

**Comment by zmarois** [comment]
1. I'm not sure if you are saying "I don't want to document the serverless approach, SAM ALL THE WAY" or "The two approaches are effectively the same, so one doc can apply to both".

If the latter, I completely agree. If the former, I disagree (not a fan of SAM compared to serverless, just seems like an unnecessary layer), but whatever. I can convert whatever you write about SAM to serverless format. 

Agreed on the rest.

**Comment by chrisoverzero** [comment]
Oh, ha, ha! I did indeed mean the former. Curiously, I'd give the same reason for favoring SAM over serverless.

Okey-doke, I'll scrap the docs re-org and put those words on the disambiguation page.

**Comment by chrisoverzero** [comment]
This is now done. 👍
